### PR TITLE
various minor fixes

### PR DESCRIPTION
**Pull request by waldyrious**
also deleted the empty "About" section at the end

### CODE REVIEW

**Comment by DThiebaud** [comment]
On 3/21/2015 11:28 PM, Waldir Pimenta wrote:
>
> also deleted the empty "About" section at the end
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/aidin36/tocc/pull/117
>
>
>         Commit Summary
>
>   * various minor fixes
>
>
>         File Changes
>
>   * *M* docs/source/index.rst
>     <https://github.com/aidin36/tocc/pull/117/files#diff-0> (31)
>
>
>         Patch Links:
>
>   * https://github.com/aidin36/tocc/pull/117.patch
>   * https://github.com/aidin36/tocc/pull/117.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aidin36/tocc/pull/117>.
>
Does anyone know if Aidin is around?

**Comment by waldyrious** [comment]
@DThiebaud apparently he abruptly stopped his github activity this January, after being fairly regularly active previously (see his contribution graph at @aidin36). He does seems active on Twitter, though ([favorited a tweet from 17 march](https://twitter.com/aidin_36/favorites)), so I [sent him a tweet](), hopefully he'll respond soon :)

**Comment by waldyrious** [comment]
Hey @aidin36, any chance you could review this? These are mostly small wording adjustments, so hopefully it won't take up much time :)

**Comment by aidin36** [comment]
Sorry that it took me five years to get back to you!

**Pull request merged**
